/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "secondary-fixed-dim": "#9ecaff",
        "surface-strong": "#e8e8e8",
        "on-tertiary-fixed-variant": "#484645",
        "surface-container": "#f1edec",
        "on-primary-fixed-variant": "#474746",
        tertiary: "#000000",
        "primary-container": "#1c1b1b",
        "on-surface": "#1c1b1b",
        "on-primary-container": "#858383",
        "surface-variant": "#e5e2e1",
        secondary: "#326190",
        "secondary-fixed": "#d1e4ff",
        "primary-fixed": "#e5e2e1",
        "surface-dark": "#222222",
        "on-tertiary-fixed": "#1c1b1a",
        "tertiary-fixed-dim": "#cac6c4",
        "primary-fixed-dim": "#c8c6c5",
        "on-primary": "#ffffff",
        "on-secondary": "#ffffff",
        "link-active": "#1a3855",
        primary: "#000000",
        error: "#ba1a1a",
        "surface-container-high": "#ebe7e6",
        "outline-variant": "#c4c7c7",
        "on-background": "#1c1b1b",
        outline: "#747878",
        body: "#4a4a4a",
        "inverse-primary": "#c8c6c5",
        "secondary-container": "#9ecaff",
        "on-tertiary": "#ffffff",
        "surface-tint": "#5f5e5e",
        "on-tertiary-container": "#868382",
        "on-secondary-fixed-variant": "#134977",
        "error-container": "#ffdad6",
        "surface-bright": "#fdf8f8",
        "surface-container-low": "#f7f3f2",
        "surface-container-highest": "#e5e2e1",
        "inverse-on-surface": "#f4f0ef",
        "inverse-surface": "#313030",
        "on-error-container": "#93000a",
        "signature-biophilic": "#3a5f4c",
        "surface-container-lowest": "#ffffff",
        "signature-drafting": "#2d5d8c",
        ink: "#1a1a1a",
        surface: "#fdf8f8",
        hairline: "#e0e0e0",
        "on-secondary-fixed": "#001d36",
        "tertiary-container": "#1c1b1a",
        background: "#fdf8f8",
        muted: "#757575",
        "surface-soft": "#f3f3f3",
        "on-surface-variant": "#444748",
        "on-primary-fixed": "#1c1b1b",
        "on-secondary-container": "#235583",
        canvas: "#fafafa",
        "surface-dim": "#ddd9d8",
        "signature-concrete": "#d1d1d1",
        "tertiary-fixed": "#e6e2df",
        "on-error": "#ffffff"
      },
      borderRadius: {
        DEFAULT: "0px",
        lg: "0px",
        xl: "0px",
        full: "0px"
      },
      spacing: {
        lg: "48px",
        margin: "48px",
        xxl: "96px",
        xxs: "4px",
        xs: "8px",
        gutter: "24px",
        section: "120px",
        md: "24px",
        sm: "16px",
        xl: "64px"
      },
      fontFamily: {
        "display-xl": ["'Tiempos Headline'", "var(--font-playfair)", "serif"],
        "display-lg": ["'Tiempos Headline'", "var(--font-playfair)", "serif"],
        "display-md": ["'Tiempos Headline'", "var(--font-playfair)", "serif"],
        "title-lg": ["'Tiempos Headline'", "var(--font-playfair)", "serif"],
        "title-md": ["'Tiempos Headline'", "var(--font-playfair)", "serif"],
        "headline-lg-mobile": ["'Tiempos Headline'", "var(--font-playfair)", "serif"],
        "body-md": ["'Tiempos Headline'", "var(--font-playfair)", "serif"],
        "mono-spec": ["var(--font-chivo-mono)", "monospace"],
        "button": ["var(--font-chivo-mono)", "monospace"],
        "label-caps": ["var(--font-chivo-mono)", "monospace"]
      },
      fontSize: {
        "display-xl": ["48px", { "lineHeight": "1.1", "letterSpacing": "-1px", "fontWeight": "300" }],
        "display-lg": ["40px", { "lineHeight": "1.2", "letterSpacing": "-0.5px", "fontWeight": "400" }],
        "display-md": ["32px", { "lineHeight": "1.2", "letterSpacing": "0", "fontWeight": "400" }],
        "title-lg": ["24px", { "lineHeight": "1.35", "letterSpacing": "0", "fontWeight": "500" }],
        "title-md": ["20px", { "lineHeight": "1.5", "letterSpacing": "0", "fontWeight": "500" }],
        "body-md": ["15px", { "lineHeight": "1.6", "letterSpacing": "0", "fontWeight": "400" }],
        "mono-spec": ["13px", { "lineHeight": "1.4", "letterSpacing": "0.5px", "fontWeight": "400" }],
        "button": ["14px", { "lineHeight": "1.4", "letterSpacing": "1px", "fontWeight": "500", "textTransform": "uppercase" }],
        "headline-lg-mobile": ["32px", { "lineHeight": "1.2", "letterSpacing": "0", "fontWeight": "400" }],
        "label-caps": ["14px", { "lineHeight": "1.4", "letterSpacing": "1px", "fontWeight": "500" }]
      }
    }
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
};
